baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-GB
name: 'Craft Boilerplate'
primary: true
siteGroup: f0e8fcd4-1f08-42e2-99c2-21be8b327aa8 # Craft Boilerplate
sortOrder: 1
