dateModified: 1631546330
email:
  fromEmail: admin@admin.com
  fromName: 'Craft Boilerplate'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    5c1c9038-bdba-49ec-9f34-31445aa94adb: 'Public Schema' # Public Schema
    cdf2ecd8-c4bb-4cab-8081-5909e79654ee: Common # Common
    d734662a-0dcd-4fe1-a959-5bcd1c43c55d: 'Craft Boilerplate' # Craft Boilerplate
    f3c5a663-2b53-4771-89f2-4276d81adbff: 'Craft Boilerplate' # Craft Boilerplate
system:
  edition: solo
  live: true
  name: 'Craft Boilerplate'
  schemaVersion: 3.7.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
